### ISSUE TITLE
Can't memcpy in general

### ISSUE THREAD

**Issue by MichaelCook** [coax1d/andrew_cpp_library#1]
https://github.com/coax1d/andrew_cpp_library/blob/e2f44b32b3b22571d6806682ddc6e0fb238c1772/Queue/Queue.hpp#L103

The memcpy will work right only for certain kinds of T objects.
Usually, all you want is plain old assignment `a = b;`

You've basically re-implemented std::deque or std::list, no?

**Comment by coax1d** [comment]
Ya, got asked in interview so thought Id do it from scratch. Going to re-do with a circular buffer as well.

**Comment by coax1d** [comment]
Fixed!
