### ISSUE TITLE
Use T&&

### ISSUE THREAD

**Issue by MichaelCook** [coax1d/andrew_cpp_library#4]
https://github.com/coax1d/andrew_cpp_library/blob/998598372dbce412e96254af4f8d1dc4831f36e8/Queue/Queue.hpp#L15

When using a template parameter like T here, instead of T& you generally want to use T&&.
This is sometimes called a universal reference.
Unlike `string&&` (i.e., with a concrete type), `T&&` (with a template parameter) does the right thing even with const objects.

**Comment by MichaelCook** [comment]
You won't need `void Queue<T>::put_queue(T &item)` anymore.
Only `void Queue<T>::put_queue(T &&item)`.

**Comment by coax1d** [comment]
with those two changes test fails on test2

**Comment by coax1d** [comment]
oh nvm need to remove the param and just leave the two ampersands

**Comment by MichaelCook** [comment]
https://godbolt.org/z/GxsW35KKa
