### ISSUE TITLE
Use smart pointers

### ISSUE THREAD

**Issue by MichaelCook** [coax1d/andrew_cpp_library#5]
https://github.com/coax1d/andrew_cpp_library/blob/998598372dbce412e96254af4f8d1dc4831f36e8/Queue/Queue.hpp#L107

It would be a worthwhile exercise to rewrite this Queue class to use smart pointers instead of legacy pointers.
Be careful about circular references which would cause memory leaks.
Consider running your test program via `valgrind` or compile with `-fsanitize=address`.

**Comment by coax1d** [comment]
Ya I was considering re-using with smart pointers. Shared pointer would work.
