### ISSUE TITLE
front_queue_, back_queue_ never hold an item

### ISSUE THREAD

**Issue by MichaelCook** [coax1d/andrew_cpp_library#8]
https://github.com/coax1d/andrew_cpp_library/blob/998598372dbce412e96254af4f8d1dc4831f36e8/Queue/Queue.hpp#L36

The ListNode<T> object pointed at by front_queue_ never holds an actual `item`.
So, it's a wasted heap allocation.
Likewise for back_queue_.

**Comment by coax1d** [comment]
What do you suggest instead of writing a separate struct that holds only a next pointer?

**Comment by MichaelCook** [comment]
Instead of
```
    front_queue_->next_ = new_node;
```
you can just do
```
    front_queue_ = new_node;
```
